<link href="/news/special/2013/newsspec_4950/css/main.css" rel="stylesheet" type="text/css" /> 
<!--no-js-->
<p id="newsspec_4950_no-js">In order to see this content you need to have <a href="http://www.bbc.co.uk/webwise/askbruce/articles/browse/java_1.shtml" title="BBC Webwise article about enabling javascript">Javascript</a> enabled. Visit <a href="http://www.bbc.co.uk/webwise/">BBC Webwise</a> for full instructions.
</p> 
<!--/no-js-->

<!--project wrapper-->
<div id="newsspec_4950">
    <!--header-->
    <div class="introduction">
        <h2 class="introduction__title">How many people like you are unemployed?</h2>
        <p class="introduction__text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore 
            et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.</p>
        <p class="introduction__text--bold">Find out the ﬁgure for people like you by selection your details from the options below.</p>
    </div>
    <!--/header-->

    <!--choices-->
    <div class="choices"> 
        <!--gender choices-->              
        <div class="choices__gender">
            <h3 class="choices__gender-header">Gender</h3>
            <form class="choices__gender-select" action="">
                <div class="choices__gender-select-item">
                    <input type="radio" name="gender" value="M"/>
                    <label for="male">Male</label>
                </div>
                <div class="choices__gender-select-item choices__gender-select-item--female">
                    <input type="radio" name="gender" value="F"/>
                    <label for="female">Female</label>
                </div>
                <!--br class= "clear" /-->
            </form>
        </div>
        <!--/gender choices-->

        <!--location choices-->
        <div class="choices__location">
            <h3 class="choices__location-header">Location</h3>
            <div class="choices__location-dropdown">
                <span>Select...</span>
            </div>
            <ul class="choices__location-list list">    
                    <li>East</li>
                    <li>East Midlands</li>
                    <li>London</li>
                    <li>North East</li>
                    <li>North West</li>
                    <li>Northern Ireland</li>
                    <li>Scotland</li>
                    <li>South East</li>
                    <li>South West</li>
                    <li>Wales</li>
                    <li>West Midlands</li>
                    <li>Yorkshire and The Humber</li>
                </ul>
        </div>
        <!--/location choices-->

        <!--occupation choices--> 
        <div class="choices__occupation">
            <h3 class="choices__occupation-header">Occupation</h3>
            <div class="choices__occupation-dropdown">
                <span>Select...</span>
            </div>
            <!--options-->
            <ul class="choices__occupation-list list">
                <!--#include virtual="/news/special/2013/newsspec_4950/inc/occupation-list.inc" -->
                <li id="12">
                    <div class="head">Managers, agriculture & services</div>
                    <div class="subhead">Farm managers, Leisure services, Publicans</div>
                </li>
                <li id="11" class="narrow">
                    <div class="head">Managers</div>
                    <div class="subhead">Government officials, Managers</div>
                </li>
                <li id="23"><div class="head">Teachers & lecturers</div></li>                       
                <li id="34" class="narrow"><div class="head">Media & sport</div></li>
                <li id="24">
                    <div class="head">Business/public service profs</div>
                    <div class="subhead">Accountants, Lawyers, Librarians, Social work</div>
                </li>
                <li id="21" class="narrow">
                    <div class="head">Science & tech profs</div>
                    <div class="subhead">Dentists, Doctors, Engineers, Vets</div>
                </li>
                <li id="31">
                    <div class="head">Science/technology assoc profs</div>
                    <div class="subhead">IT support, Lab technicians</div>
                </li>                        
                <li id="71" class="narrow">
                    <div class="head">Sales</div>
                    <div class="subhead">Retail assistant</div>
                </li>
                <li id="35">
                    <div class="head">Business/public service assoc profs</div>
                    <div class="subhead">Brokers, Estate agents, Train drivers</div>
                </li>                        
                <li id="41" class="narrow">
                    <div class="head">Admin occupations</div>
                    <div class="subhead">Civil service, Clerks, Telephonists</div>
                </li>
                <li id="42"><div class="head">Secretarial</div></li>                        
                <li id="33" class="narrow"><div class="head">Emergency services</div></li>
                <li id="51"><div class="head">Skilled agricultural trades</div></li>
                <li id="82" class="narrow"><div class="head">Transport</div></li>
                <li id="92">
                    <div class="head">Elementary admin/services</div>
                    <div class="subhead">Bar/restaurant staff, Postal work, Security guard</div>
                </li>                        
                <li id="52" class="narrow">
                    <div class="head">Skilled trades</div>
                    <div class="subhead">Electricians, Metal workers</div>
                </li>                        
                <li id="54"><div class="head">Textile, printing, other skilled trades</div></li>
                <li id="53" class="narrow"><div class="head">Skilled building trades</div></li>
                <li id="61"><div class="head">Caring service occupations</div><div class="subhead">Nursery nurses, childminders</div></li>
                <li id="62" class="narrow"><div class="head">Leisure</div><div class="subhead">Hairdressers, Travel agents</div></li>                        
                <li id="32"><div class="head">Healthcare associate profs</div><div class="subhead">Nurses, midwives and physios</div></li>
                <li id="91" class="narrow"><div class="head">Elementary trades</div><div class="subhead">Labourers, Packers</div></li>
                <li id="72"><div class="head">Customer service, call centres</div></li>
                <li id="81" class="narrow"><div class="head">Plant work</div></li>
            </ul>
            <!--/options-->
        </div>             
        <br class="clear" />
    </div>
    <!--/choices-->

    <!--results-->
    <div class="results">
        <!--default-->
        <div class="results__default"></div>
        <!--/default-->

        <!--all-->
        <div class="results__all">
            <h3 class="results__all-header">Jobseekers allowance: Your selection</h3>
            <div class="results__all-item results__all-gender">
                <h4 class="results__all-your-choice">Men</h4>
                <div class="results__all-absolute">
                    <h4 class="percentage">6%</h4>
                    <h4 class="number">600,000 claims</h4>
                </div>
                <div class="results__all-relative">
                    <h4 class="up">1.2%</h4>
                    <p>Annual<br/>change</p>
                </div>
                <div class="results__all-history">
                    <p class="last-year">One year ago: <span>7.0%</span></p>
                    <p class="five-years-ago">Five years ago: <span>8.2%</span></p>
                </div>
            </div>
            <!--end of gender results-->

            <div class="results__all-item results__all-location">
                <h4 class="results__all-your-choice">London</h4>
                <div class="results__all-absolute">
                    <h4 class="percentage">6%</h4>
                    <h4 class="number">600,000 claims</h4>
                </div>
                <div class="results__all-relative">
                    <h4 class="down">1.2%</h4>
                    <p>Annual<br/>change</p>
                </div>
                <div class="results__all-history">
                    <p class="last-year">One year ago: <span>7.0%</span></p>
                    <p class="five-years-ago">Five years ago: <span>8.2%</span></p>
                </div>
            </div> 
            <!--end of locations results-->

            <div class="results__all-item results__all-occupation">
                <h4 class="results__all-your-choice">Corporate management</h4>
                <div class="results__all-absolute">
                    <h4 class="percentage">56%</h4>
                    <h4 class="number">600,000 claims</h4>
                </div>
                <div class="results__all-relative">
                    <h4 class="down">1.2%</h4>
                    <p>Annual<br/>change</p>
                </div>
                <div class="results__all-history">
                    <p class="last-year">One year ago: <span>7.0%</span></p>
                    <p class="five-years-ago">Five years ago: <span>8.2%</span></p>
                </div>
            </div>
            <!--end of occupations results-->

        </div>
        <!--/all-->               
    </div> 
    <!--/results-->
    <!--share-->
    <div class="share-results">
    </div>
    <!--/share-->

    <!--chart-->           
    <div id="line-chart"></div>
    <!--/chart--> 

    <!--bubble chart-->
    <div id="bubble-chart--loc" class="bubble-chart">
        <div class="tip-key" style="display: none">
            <div class="tip-content"></div>
            <div class="tip-beak"></div>
        </div>
        <div class="choice-key" style="display: none">
            <div class="choice-content"></div>
            <div class="choice-beak"></div>
        </div>
        <div class="tip-value" style="display: none"></div>
        <div class="choice-value" style="display: none"></div>
    </div>
    <div id="bubble-chart--occ" class="bubble-chart">
        <div class="tip-key" style="display: none">
            <div class="tip-content"></div>
            <div class="tip-beak"></div>
        </div>
        <div class="choice-key" style="display: none">
            <div class="choice-content"></div>
            <div class="choice-beak"></div>
        </div>
        <div class="tip-value" style="display: none"></div>
        <div class="choice-value" style="display: none"></div>
    </div>
    <!--/bubble charts-->

    </div>
    <!--/project wrapper-->

    <script type="text/javascript" src="/news/special/2013/newsspec_4950/js/main.js"></script>