<li id="12">
    <div class="head">Managers, agriculture & services</div>
    <div class="subhead">Farm managers, Leisure services, Publicans</div>
</li>
<li id="11" class="narrow">
    <div class="head">Managers</div>
    <div class="subhead">Government officials, Managers</div>
</li>
<li id="23"><div class="head">Teachers & lecturers</div></li>                       
<li id="34" class="narrow"><div class="head">Media & sport</div></li>
<li id="24">
    <div class="head">Business/public service profs</div>
    <div class="subhead">Accountants, Lawyers, Librarians, Social work</div>
</li>
<li id="21" class="narrow">
    <div class="head">Science & tech profs</div>
    <div class="subhead">Dentists, Doctors, Engineers, Vets</div>
</li>
<li id="31">
    <div class="head">Science/technology assoc profs</div>
    <div class="subhead">IT support, Lab technicians</div>
</li>                        
<li id="71" class="narrow">
    <div class="head">Sales</div>
    <div class="subhead">Retail assistant</div>
</li>
<li id="35">
    <div class="head">Business/public service assoc profs</div>
    <div class="subhead">Brokers, Estate agents, Train drivers</div>
</li>                        
<li id="41" class="narrow">
    <div class="head">Admin occupations</div>
    <div class="subhead">Civil service, Clerks, Telephonists</div>
</li>
<li id="42"><div class="head">Secretarial</div></li>                        
<li id="33" class="narrow"><div class="head">Emergency services</div></li>
<li id="51"><div class="head">Skilled agricultural trades</div></li>
<li id="82" class="narrow"><div class="head">Transport</div></li>
<li id="92">
    <div class="head">Elementary admin/services</div>
    <div class="subhead">Bar/restaurant staff, Postal work, Security guard</div>
</li>                        
<li id="52" class="narrow">
    <div class="head">Skilled trades</div>
    <div class="subhead">Electricians, Metal workers</div>
</li>                        
<li id="54"><div class="head">Textile, printing, other skilled trades</div></li>
<li id="53" class="narrow"><div class="head">Skilled building trades</div></li>
<li id="61"><div class="head">Caring service occupations</div><div class="subhead">Nursery nurses, childminders</div></li>
<li id="62" class="narrow"><div class="head">Leisure</div><div class="subhead">Hairdressers, Travel agents</div></li>                        
<li id="32"><div class="head">Healthcare associate profs</div><div class="subhead">Nurses, midwives and physios</div></li>
<li id="91" class="narrow"><div class="head">Elementary trades</div><div class="subhead">Labourers, Packers</div></li>
<li id="72"><div class="head">Customer service, call centres</div></li>
<li id="81" class="narrow"><div class="head">Plant work</div></li>